[tool.poetry]
name = "watchdogs2"
version = "0.1.0"
description = ""
authors = ["HorseTI"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
